import type { FoodVendor } from "./types"

export const foodVendors: FoodVendor[] = [
  {
    name: "WAROENG MANIEZ",
    description: "Kantin lt.10",
    menu: [
      { item: "[PAKET 1] Nasi Putih, Sayuran, Telur", price: 15000 },
      { item: "[PAKET 2] Nasi Putih, Sayuran, Ayam/Ikan", price: 25000 },
      { item: "Nasi Putih", price: 5000 },
      { item: "Sayur[Lodeh/Asam/Sop]", price: 5000 },
      { item: "Telur", price: 5000 },
      { item: "Ayam/Ikan", price: 10000 },
      { item: "Perkedel", price: 3000 },
      { item: "Gorengan", price: 3000 },
    ],
  },
  {
    name: "JJS KITCHEN",
    description: "Kantin lt.10",
    menu: [
      { item: "Gyoza Chili Oil", price: 15000 },
      { item: "Risoles", price: 5000 },
      { item: "Takoyaki", price: 10000 },
      { item: "Indomie Rebus", price: 7000 },
      { item: "Indomie Goreng", price: 7000 },
      { item: "Indomie Telur", price: 10000 },
      { item: "Indomie Telur Keju", price: 13000 },
      { item: "Indomie Telur Kornet", price: 15000 },
      { item: "Indomie Telur Kornet Keju", price: 18000 },
    ],
  },
  {
    name: "",
    description: "Kantin lt.10",
    menu: [
      { item: "Roti-O", price: 6000 },
      { item: "Singkong Thailand", price: 13000 },
      { item: "Dimsum", price: 13000 },
      { item: "Nasi Bakar Ayam/Teri", price: 10000 },
      { item: "Siomay", price: 13000 },
    ],
  },
  {
    name: "GULTIK BONANG",
    description: "Kantin lt.10",
    menu: [
      { item: "Paket Nasi Gule Ayam", price: 18000 },
      { item: "Paket Nasi Gule Sapi", price: 20000 },
      { item: "Paket Nasi Ayam Kremes", price: 25000 },
      { item: "Paket Nasi Telur Kribo", price: 15000 },
      { item: "Telur Asin", price: 7000 },
      { item: "Peyek", price: 5000 },
      { item: "Sate Jerohan", price: 3000 },
      { item: "Sayur Asam", price: 3000 },
      { item: "Gorengan", price: 3000 },
    ],
  },
  {
    name: "PIPPOP's",
    description: "Kantin lt.10",
    menu: [
      { item: "Chicken Steak", price: 20000 },
      { item: "Crispy Steak", price: 20000 },
      { item: "Chicken Skin", price: 15000 },
      { item: "Nasi Ayam Mix", price: 18000 },
      { item: "Chicken Pop", price: 16000 },
      { item: "Chicken Bubble", price: 17000 },
      { item: "Shihlin", price: 17000 },
      { item: "Katsu", price: 17000 },
      { item: "Onion Ring", price: 15000 },
      { item: "Spaghetti", price: 17000 },
      { item: "French Fries", price: 13000 },
    ],
  },
  {
    name: "BAKSO MINUL KHAS PONTIANAK",
    description: "Kantin lt.10",
    menu: [
      { item: "[Paket] Bakso Urat", price: 25000 },
      { item: "[Paket] Bakso Daging", price: 25000 },
      { item: "[Paket] Bakso Telu", price: 25000 },
      { item: "[Paket] Bakso Jumbo", price: 28000 },
      { item: "[Paket] Bakso Kecil", price: 22000 },
      { item: "[Paket] Bakso Melilit", price: 10000 },
      { item: "[Tambahan] Kwetiau", price: 4000 },
      { item: "[Tambahan] Nasi Putih", price: 4000 },
      { item: "[Tambahan] Bihun", price: 4000 },
      { item: "[Tambahan] Indomie Kuah", price: 6000 },
      { item: "[Tambahan] Indomie Goreng", price: 6000 },
      { item: "[Tambahan] Pop Mie", price: 10000 },
      { item: "[Tambahan] Bakso", price: 14000 },
      { item: "[Tambahan] Bakso Daging", price: 14000 },
      { item: "[Tambahan] Bakso Telur", price: 14000 },
      { item: "[Tambahan] Tahu Bakso", price: 6000 },
      { item: "[Tambahan] Bakso Kerikil", price: 8000 },
      { item: "[Tambahan] Bakso Gepeng", price: 8000 },
    ],
  },
  {
    name: "CREPES TIME",
    description: "Kantin lt.10",
    menu: [
      { item: "Crepes Polos", price: 10000 },
      { item: "[Topping] Selai Coklat", price: 4000 },
      { item: "[Topping] Selai Strawberry", price: 4000 },
      { item: "[Topping] Selai Blueberry", price: 4000 },
      { item: "[Topping] Meses", price: 4000 },
      { item: "[Topping] Choco-Chip", price: 5000 },
      { item: "[Topping] Pisang", price: 5000 },
      { item: "[Topping] Keju", price: 5000 },
      { item: "[Topping] Selai Kacang", price: 5000 },
      { item: "[Topping] Nutella", price: 5000 },
      { item: "[Topping] Tiramisu", price: 5000 },
      { item: "[Topping] Choco Crunch", price: 5000 },
      { item: "[Topping] Milo", price: 5000 },
      { item: "[Topping] Milk Crunchy", price: 5000 },
      { item: "[Topping] Taro", price: 5000 },
      { item: "[Topping] Ovaltine", price: 5000 },
      { item: "[Topping] Green Tea", price: 5000 },
      { item: "[Topping] Cheese Spread", price: 5000 },
      { item: "[Topping] Susu", price: 2000 },
    ],
  },
  {
    name: "HOLY KEBAB & BURGER",
    description: "Kantin lt.10",
    menu: [
      { item: "Holy Kebab Beef Reguler", price: 15000 },
      { item: "Holy Kebab Beef Large", price: 18000 },
      { item: "Holy Kebab Chicken Reguler", price: 15000 },
      { item: "Holy Kebab Chicken Large", price: 18000 },
      { item: "Holy Kebab Sosis Reguler", price: 15000 },
      { item: "Holy Kebab Sosis Large", price: 18000 },
      { item: "Holy Burger Beef", price: 15000 },
      { item: "Holy Burger Beef Cheese", price: 18000 },
      { item: "Holy Burger Chicken Cheese", price: 18000 },
    ],
  },
  {
    name: "Ayam Geprek dan Soto Semarang",
    description: "Kantin B1",
    menu: [
      { item: "Soto Semarang (Ayam)", price: 17000 },
      { item: "Soto Semarang (Ayam) + Nasi Campur", price: 19000 },
      { item: "Soto Semarang (Ayam) + Nasi Pisah", price: 22000 },
      { item: "Soto Semarang (Daging)", price: 20000 },
      { item: "Soto Semarang (Daging) + Nasi Campur", price: 22000 },
      { item: "Soto Semarang (Daging) + Nasi Pisah", price: 25000 },
      { item: "Nasi Putih", price: 5000 },
      { item: "Perkedel Kentang Polos", price: 5000 },
      { item: "Perkedel Kentang Kornet", price: 6000 },
      { item: "Perkedel Kentang Ayam", price: 6000 },
      { item: "Sate Telur Puyuh", price: 6000 },
      { item: "Sate Ati", price: 5000 },
      { item: "Sate Ampela", price: 5000 },
      { item: "Sate Kerang", price: 5000 },
      { item: "Tahu Bacem", price: 8000 },
      { item: "Tempe Bacem", price: 8000 },
      { item: "Tempe Goreng", price: 8000 },
      { item: "Kerupuk Putih", price: 3000 },
      { item: "Karak (Kerupuk Beras)", price: 5000 },
      { item: "Kerupuk Kedelai", price: 4000 },
      { item: "Emping", price: 6000 },
      { item: "Kacang Atom Jambu", price: 8000 },
    ],
  },
  {
    name: "BAKMI Q-TA",
    description: "Kantin B1",
    menu: [
      { item: "Mie Ayam Original", price: 17000 },
      { item: "Kwetiau Original", price: 19000 },
      { item: "Bihun Ayam Original", price: 18000 },
      { item: "Mie Ayam Spesial", price: 22000 },
      { item: "Kwetiau Spesial", price: 24000 },
      { item: "Bihun Ayam Spesial", price: 23000 },
      { item: "Mie Ayam Yamin", price: 18000 },
      { item: "Kwetiau Yamin", price: 20000 },
      { item: "Bihun Ayam Yamin", price: 19000 },
      { item: "Mie Ayam Yamin Spesial", price: 23000 },
      { item: "Kwetiau Yamin Spesial", price: 25000 },
      { item: "Bihun Ayam Yamin Spesial", price: 24000 },
      { item: "Mie Ayam Jumbo", price: 22000 },
      { item: "Kwetiau Jumbo", price: 24000 },
      { item: "Bihun Ayam Jumbo", price: 23000 },
      { item: "Mie Ayam Jumbo Spesial", price: 27000 },
      { item: "Kwetiau Jumbo Spesial", price: 29000 },
      { item: "Bihun Ayam Jumbo Spesial", price: 28000 },
      { item: "Mie Ayam Geprek/Chili Oil", price: 20000 },
      { item: "Kwetiau Geprek/Chili Oil", price: 22000 },
      { item: "Bihun Ayam Geprek/Chili Oil", price: 21000 },
      { item: "Mie Ayam Chili Oil Jumbo", price: 25000 },
      { item: "Pangsit Kuah (5pcs)", price: 15000 },
      { item: "Pangsit + Bakso Kuah (5pcs)", price: 15000 },
    ],
  },
  {
    name: "CLAUDE KITCHEN",
    description: "Kantin B1",
    menu: [
      { item: "[PAKET HEMAT] Nasi Hainan Ayam Charsiu", price: 21000 },
      { item: "[PAKET HEMAT] Nasi Hainan Ayam Rebus", price: 21000 },
      { item: "[PAKET HEMAT] Nasi Hainan Ayam Gohiong", price: 21000 },
      { item: "[PAKET HEMAT] Nasi Hainan Ayam Goreng Bawang Putih", price: 21000 },
      { item: "[PAKET HEMAT] Nasi Hainan Sate Ayam", price: 25000 },
      { item: "[PAKET HEMAT] Nasi Hainan Ayam Panggang", price: 25000 },
      { item: "[PAKET] Nasi Hainan 2 Topping", price: 27000 },
      { item: "[PAKET] Nasi Hainan 3 Topping", price: 30000 },
      { item: "[PAKET] Nasi Hainan Spesial", price: 35000 },
      { item: "Aneka Ayam", price: 10000 },
      { item: "Nasi Putih", price: 5000 },
      { item: "Nasi Hainan", price: 7000 },
      { item: "Sayur Asin", price: 5000 },
    ],
  },
  {
    name: "AYURA | MASAKAN PADANG",
    description: "Kantin B1",
    menu: [
      { item: "Ayam Bakar", price: 25000 },
      { item: "Ayam Bumbu", price: 22000 },
      { item: "Telur Barendo", price: 15000 },
      { item: "Rendang", price: 27000 },
      { item: "Telur Puyuh Balado", price: 15000 },
      { item: "Dendeng Balado", price: 27000 },
      { item: "Perkedel", price: 5000 },
    ],
  },
  {
    name: "",
    description: "Kantin B1",
    menu: [
      { item: "Nasi Goreng Telur", price: 18000 },
      { item: "Nasi Goreng Bakso", price: 18000 },
      { item: "Nasi Goreng Ayam", price: 18000 },
      { item: "Nasi Goreng Sosis", price: 18000 },
      { item: "Nasi Goreng Chicken Nugget", price: 18000 },
      { item: "Nasi Goreng Ati Ampela", price: 18000 },
      { item: "Nasi Goreng Kornet", price: 18000 },
      { item: "Nasi Goreng Gila", price: 20000 },
      { item: "Nasi Goreng Smooked Beef", price: 20000 },
    ],
  },
  {
    name: "",
    description: "Kantin B1",
    menu: [
      { item: "Tahu Gejrot", price: 10000 },
      { item: "Bakwan Malang", price: 17000 },
      { item: "Bakso Tahu", price: 14000 },
      { item: "Bakso Sapi", price: 14000 },
    ],
  },
  {
    name: "SIOMAY PALACE",
    description: "Kantin B1",
    menu: [
      { item: "Siomay", price: 5000 },
      { item: "Siomay Sosis", price: 5000 },
      { item: "Siomay Mozarella", price: 5000 },
      { item: "Siomay Bakso", price: 5000 },
      { item: "Siomay Telur", price: 5000 },
      { item: "Siomay Tahu", price: 5000 },
      { item: "Kentang", price: 5000 },
      { item: "[Paket] Isi 4 Pcs", price: 18000 },
      { item: "[Paket] Isi 5 Pcs", price: 22000 },
    ],
  },
  {
    name: "NASI PECEL BANG SHOPA",
    description: "Kantin B1",
    menu: [
      { item: "Nasi Pecel", price: 12000 },
      { item: "Nasi Pecel Telur Dadar", price: 16000 },
      { item: "Nasi Pecel Telur Balado", price: 16000 },
      { item: "Nasi Pecel Tongkol", price: 16000 },
      { item: "Nasi Pecel Ati Ampela", price: 17000 },
      { item: "Nasi Pecel Ayam Goreng", price: 20000 },
      { item: "Nasi Pecel Ayam Bakar", price: 20000 },
      { item: "Aneka Gorengan", price: 2000 },
    ],
  },
  {
    name: "PEMPEK BANGKA CIA-CIA",
    description: "Kantin B1",
    menu: [
      { item: "Pempek Telur Besar", price: 13000 },
      { item: "Pempek Lenjer Besar", price: 8000 },
      { item: "Pempek Telur Kecil", price: 7000 },
      { item: "Pempek Lenjer Kecil", price: 3000 },
      { item: "Pempek Adaan", price: 3000 },
      { item: "Pempek Kulit", price: 3000 },
      { item: "Tekwan", price: 15000 },
    ],
  },
  {
    name: "",
    description: "Kantin B1",
    menu: [
      { item: "Kebab Beef", price: 18000 },
      { item: "Kebab Chicken", price: 15000 },
      { item: "Burger Beef", price: 18000 },
      { item: "Burger Chicken", price: 15000 },
      { item: "Burger Crispy Chick", price: 15000 },
      { item: "Burger Cheese with Egg", price: 20000 },
      { item: "Hotdog Sosis", price: 15000 },
      { item: "[Topping] Keju", price: 2000 },
      { item: "[TOPPING] Mozarella", price: 3000 },
    ],
  },
  {
    name: "SOTO KUDUS PAK RAMIDJAN",
    description: "Kantin B1",
    menu: [
      { item: "Soto Kudus", price: 18000 },
      { item: "Pindang Kudus", price: 20000 },
      { item: "Tahu Telur", price: 14000 },
      { item: "Garang Asem Ayam", price: 25000 },
      { item: "Ayam Kalasan", price: 19000 },
      { item: "Ayam Penyet", price: 19000 },
      { item: "Ayam Saos Padang", price: 20000 },
      { item: "Soto Kudus + Nasi", price: 22000 },
      { item: "Pindang Kudus + Nasi", price: 22000 },
      { item: "Tahu Telur + Nasi", price: 18000 },
      { item: "Garang Asem Ayam + Nasi", price: 30000 },
      { item: "Ayam Kalasan + Nasi", price: 23000 },
      { item: "Ayam Penyet + Nasi", price: 23000 },
      { item: "Ayam Saos Padang + Nasi", price: 25000 },
      { item: "Nasi 1/2 Porsi", price: 4000 },
      { item: "Nasi Putih", price: 6000 },
      { item: "Lontong", price: 3000 },
    ],
  },
  {
    name: "WAKARI",
    description: "Kantin B1",
    menu: [
      { item: "Mie Kari Ori", price: 18000 },
      { item: "Mie Kari Komplit", price: 23000 },
      { item: "Mie Kari Katsu", price: 28000 },
      { item: "Dry Kari Ori", price: 14000 },
      { item: "Dry Kari Telur", price: 18000 },
      { item: "Dry Kari Katsu", price: 23000 },
      { item: "[EXTRA] Telur", price: 6000 },
      { item: "[EXTRA] Pangsit", price: 6000 },
      { item: "[EXTRA] Chicken Katsu", price: 12000 },
    ],
  },
  {
    name: "Sate Taichan",
    description: "Kantin B1",
    menu: [
      { item: "Taichan Ori", price: 25000 },
      { item: "Taichan Ori 1/2 Porsi", price: 14000 },
      { item: "Taichan Crispy", price: 28000 },
      { item: "Taichan Crispy 1/2 Porsi", price: 16000 },
      { item: "Otak-otak Mercon", price: 18000 },
      { item: "Bakso Mercon", price: 18000 },
    ],
  },
  {
    name: "WARUNG 78 SOTO & SOP",
    description: "Kantin B1",
    menu: [
      { item: "Soto Sapi Susu + Nasi", price: 26000 },
      { item: "Soto Ayam Susu + Nasi", price: 23000 },
      { item: "Soto Sapi Santan + Nasi", price: 26000 },
      { item: "Soto Ayam Santan + Nasi", price: 23000 },
      { item: "Sop Sapi + Nasi", price: 21000 },
      { item: "Sop Ayam + Nasi", price: 19000 },
      { item: "Rawon Sapi + Nasi", price: 25000 },
      { item: "[TAMBAHAN] Telur Asin", price: 4000 },
      { item: "[TAMBAHAN] Perkedel", price: 4000 },
      { item: "[TAMBAHAN] Kerupuk Udang", price: 4000 },
      { item: "[TAMBAHAN] Nasi Putih", price: 4000 },
    ],
  },
  {
    name: "NASI LIWET BALI",
    description: "Kantin B1",
    menu: [
      { item: "MENU 2 LAUK", price: 23000 },
      { item: "MENU 3 LAUK", price: 26000 },
      { item: "MENU 5 LAUK", price: 28000 },
      { item: "MENU 2 Sayur", price: 19000 },
      { item: "MENU 1 Lauk + 1 Sayur", price: 21000 },
      { item: "MENU 2 Lauk + 1 Sayur", price: 25000 },
      { item: "MENU 1 Lauk + 2 Sayur", price: 24000 },
    ],
  },
  {
    name: "BUBUR AYAM CENTRAL",
    description: "Kantin B1",
    menu: [
      { item: "Bubur Ayam", price: 20000 },
      { item: "Bubur Ayam + Telur", price: 24000 },
      { item: "Bubur Ayam [EXTRA AYAM]", price: 24000 },
      { item: "Bubur Ayam [EXTRA PANGSIT]", price: 24000 },
    ],
  },
  {
    name: "",
    description: "Kantin B1",
    menu: [
      { item: "Bebek Original", price: 23000 },
      { item: "Ayam Original", price: 20000 },
      { item: "Bebek Komplit", price: 27000 },
      { item: "Ayam Komplit", price: 24000 },
      { item: "Bebek Kremes", price: 25000 },
    ],
  },
  {
    name: "ROCKY ROOSTER",
    description: "Kantin B1",
    menu: [
      { item: "Dada Ayam", price: 18000 },
      { item: "Paha Atas", price: 18000 },
      { item: "Paha Bawah", price: 13000 },
      { item: "Sayap Ayam", price: 10000 },
      { item: "Nasi Putih", price: 6000 },
      { item: "Kentang Goreng", price: 12000 },
      { item: "Perkedel Ayam", price: 4000 },
      { item: "Soup Ayam", price: 10000 },
      { item: "Mozarella", price: 25000 },
      { item: "[HEMAT 1] Dada + Nasi", price: 23000 },
      { item: "[HEMAT 2] Paha Atas + Nasi", price: 23000 },
      { item: "[HEMAT 3] Paha Bawah + Nasi", price: 18000 },
      { item: "[HEMAT 4] Sayap + Nasi", price: 15000 },
      { item: "[COMBO 1] Dada + Sayap", price: 30000 },
      { item: "[COMBO 2] Paha Atas + Sayap", price: 30000 },
      { item: "[COMBO 3] Paha Bawah + Sayap", price: 27000 },
      { item: "[COMBO 4] 2 Sayap + Nasi", price: 23000 },
    ],
  },
  {
    name: "BAKMIE KIETA",
    description: "Kantin B1",
    menu: [
      { item: "Bakmi Ayam Jamur", price: 20000 },
      { item: "Kwetiau Goreng", price: 23000 },
      { item: "Mie Kuah", price: 23000 },
      { item: "Bihun Kuah", price: 23000 },
    ],
  },
  {
    name: "DAPUR PENYET",
    description: "Kantin B1",
    menu: [
      { item: "Nasi + Ayam Goreng + Tahu/Tempe", price: 28000 },
      { item: "Nasi + Ayam Bakar + Tahu/Tempe", price: 28000 },
      { item: "Nasi Ayam Bakar", price: 23000 },
      { item: "Nasi + Ayam Kremes", price: 23000 },
      { item: "Nasi + Ayam Penyet Cabe Merah", price: 23000 },
      { item: "Nasi + Ayam Penyet Cabe Ijo", price: 23000 },
      { item: "Nasi + Sayap Goreng", price: 15000 },
      { item: "Nasi + Sayap Bakar", price: 15000 },
      { item: "Nasi + Lele Goreng/Bakar", price: 18000 },
      { item: "Nasi + Nila Bakar", price: 25000 },
      { item: "Nasi + Nila Goreng", price: 25000 },
      { item: "Sayur Asam", price: 7000 },
      { item: "Terong Penyet", price: 10000 },
      { item: "Bakso Penyet", price: 10000 },
      { item: "Tempe Penyet", price: 7000 },
      { item: "Tahu Penyet", price: 7000 },
    ],
  },
]
