import type { FoodVendor } from "./types"

export const foodVendors: FoodVendor[] = [
  {
    name: "Warung Padang",
    description: "B1",
    menu: [
      { item: "Nasi Rendang", price: 25000 },
      { item: "Nasi Ayam Bakar", price: 20000 },
      { item: "Nasi Ayam Goreng", price: 18000 },
      { item: "Nasi Ikan Bakar", price: 22000 },
      { item: "Nasi Telur Balado", price: 15000 },
      { item: "Nasi Sayur", price: 12000 },
      { item: "Es Teh Manis", price: 5000 },
      { item: "Es Jeruk", price: 7000 },
    ],
  },
  {
    name: "Kantin Jepang",
    description: "B1",
    menu: [
      { item: "Chicken Katsu", price: 25000 },
      { item: "Beef Teriyaki", price: 30000 },
      { item: "Chicken Teriyaki", price: 25000 },
      { item: "Salmon Teriyaki", price: 35000 },
      { item: "Tempura", price: 20000 },
      { item: "Udon", price: 22000 },
      { item: "Ocha", price: 5000 },
      { item: "Green Tea", price: 8000 },
    ],
  },
  {
    name: "Warung Sunda",
    description: "lt.10",
    menu: [
      { item: "Nasi Timbel", price: 25000 },
      { item: "Nasi Liwet", price: 22000 },
      { item: "Nasi Tutug Oncom", price: 20000 },
      { item: "Nasi Pepes Ikan", price: 25000 },
      { item: "Nasi Pepes Ayam", price: 23000 },
      { item: "Nasi Karedok", price: 15000 },
      { item: "Es Cendol", price: 8000 },
      { item: "Es Cincau", price: 7000 },
    ],
  },
  {
    name: "Kedai Kopi",
    description: "lt.10",
    menu: [
      { item: "Espresso", price: 15000 },
      { item: "Americano", price: 18000 },
      { item: "Cappuccino", price: 22000 },
      { item: "Latte", price: 23000 },
      { item: "Mocha", price: 25000 },
      { item: "Matcha Latte", price: 25000 },
      { item: "Croissant", price: 15000 },
      { item: "Sandwich", price: 20000 },
    ],
  },
  {
    name: "Warung Mie",
    description: "B1",
    menu: [
      { item: "Mie Ayam", price: 15000 },
      { item: "Mie Ayam Bakso", price: 20000 },
      { item: "Mie Ayam Pangsit", price: 18000 },
      { item: "Bakso", price: 15000 },
      { item: "Bakso Urat", price: 18000 },
      { item: "Bakso Beranak", price: 25000 },
      { item: "Es Teh Manis", price: 5000 },
      { item: "Es Jeruk", price: 7000 },
    ],
  },
  {
    name: "Kedai Bubble Tea",
    description: "lt.10",
    menu: [
      { item: "Brown Sugar Boba", price: 22000 },
      { item: "Taro Milk Tea", price: 20000 },
      { item: "Matcha Boba", price: 23000 },
      { item: "Chocolate Boba", price: 20000 },
      { item: "Strawberry Boba", price: 20000 },
      { item: "Oreo Milk Tea", price: 25000 },
      { item: "Fruit Tea", price: 18000 },
      { item: "Cheese Tea", price: 23000 },
    ],
  },
  {
    name: "Warung Soto",
    description: "B1",
    menu: [
      { item: "Soto Ayam", price: 15000 },
      { item: "Soto Daging", price: 20000 },
      { item: "Soto Mie", price: 18000 },
      { item: "Soto Betawi", price: 22000 },
      { item: "Soto Lamongan", price: 17000 },
      { item: "Soto Kudus", price: 16000 },
      { item: "Es Teh Manis", price: 5000 },
      { item: "Es Jeruk", price: 7000 },
    ],
  },
  {
    name: "Warung Nasi",
    description: "lt.10",
    menu: [
      { item: "Nasi Goreng", price: 18000 },
      { item: "Nasi Goreng Spesial", price: 25000 },
      { item: "Nasi Ayam Geprek", price: 20000 },
      { item: "Nasi Ayam Penyet", price: 20000 },
      { item: "Nasi Ikan Bakar", price: 25000 },
      { item: "Nasi Capcay", price: 18000 },
      { item: "Es Teh Manis", price: 5000 },
      { item: "Es Jeruk", price: 7000 },
    ],
  },
]
